Repository catalystneuro/roiextractors, pull requests merged in 2022-05, with the labels that each got.

#114 re-enable check_comparisons in `test_io`
  src/roiextractors/extractors/caiman/caimansegmentationextractor.py
  src/roiextractors/testing.py
  tests/test_io.py
Labels: testing

#116 Modified import of `mat_struct` for deprecation warning
  src/roiextractors/extraction_tools.py
Labels: warnings

#115 Add read binary numpy video as stand alone
  src/roiextractors/extraction_tools.py
  tests/test_internals/__init__.py
  tests/test_internals/test_extraction_tools.py
Labels: enhancement, high priority, testing

#118 [Testing] non-memmap TIFF
  .github/workflows/testing.yml
  tests/test_io.py
Labels: testing

#113 Add `NumpyMemmapImagingExtractor`
  src/roiextractors/extractorlist.py
  src/roiextractors/extractors/memmapextractors/__init__.py
  src/roiextractors/extractors/memmapextractors/numpymemampextractor.py
  src/roiextractors/testing.py
  tests/test_numpymemmapextractor.py
Labels: enhancement, high priority

#124 Added docstring to the `read_numpy_memmap` function
  src/roiextractors/extraction_tools.py
Labels: documentation, refactor

#122 Memmap ImagingExtractor classes unification I
  requirements-minimal.txt
  src/roiextractors/extractors/memmapextractors/memmapextractors.py
  src/roiextractors/extractors/memmapextractors/numpymemampextractor.py
  tests/test_numpymemmapextractor.py
Labels: refactor
