Repository catalystneuro/roiextractors, pull requests merged in 2022-08, with the labels that each got.

#187 `SegmentationExtractor`: add frame_to_time, get_roi_ids as class methods
  CHANGELOG.md
  src/roiextractors/extractors/caiman/caimansegmentationextractor.py
  src/roiextractors/extractors/nwbextractors/nwbextractors.py
  src/roiextractors/extractors/schnitzerextractor/cnmfesegmentationextractor.py
  src/roiextractors/extractors/schnitzerextractor/extractsegmentationextractor.py
  src/roiextractors/extractors/simaextractor/simasegmentationextractor.py
  src/roiextractors/extractors/suite2p/suite2psegmentationextractor.py
  src/roiextractors/multisegmentationextractor.py
  src/roiextractors/segmentationextractor.py
  src/roiextractors/testing.py
  tests/test_internals/test_testing_tools.py
Labels: enhancement

#170 Add EXTRACT-Public support
  CHANGELOG.md
  src/roiextractors/extractorlist.py
  src/roiextractors/extractors/schnitzerextractor/__init__.py
  src/roiextractors/extractors/schnitzerextractor/extractsegmentationextractor.py
  tests/test_extractsegmentationextractor.py
  tests/test_io.py
Labels: enhancement

#200 Fix segmentation orientation
  CHANGELOG.md
  src/roiextractors/extractors/caiman/caimansegmentationextractor.py
  src/roiextractors/extractors/numpyextractors/numpyextractors.py
  src/roiextractors/extractors/schnitzerextractor/cnmfesegmentationextractor.py
  src/roiextractors/extractors/schnitzerextractor/extractsegmentationextractor.py
  src/roiextractors/extractors/suite2p/suite2psegmentationextractor.py
  src/roiextractors/segmentationextractor.py
  src/roiextractors/testing.py
  tests/test_extractsegmentationextractor.py
  tests/test_internals/test_testing_tools.py
Labels: refactor

#201 [Merge after #200]: Subframe segmentation
  CHANGELOG.md
  src/roiextractors/extractors/numpyextractors/numpyextractors.py
  src/roiextractors/segmentationextractor.py
  src/roiextractors/testing.py
  tests/test_internals/test_frame_slice_segmentation.py
  tests/test_internals/test_testing_tools.py
Labels: enhancement

#203 Debug to edge case of MultiImaging
  src/roiextractors/multiimagingextractor.py
  tests/test_internals/test_multiimagingextractor.py
Labels: bug

#207 Finish correcting segmentation orientation
  src/roiextractors/extractors/suite2p/suite2psegmentationextractor.py
  src/roiextractors/segmentationextractor.py
  tests/test_internals/test_testing_tools.py
  tests/test_io.py
Labels: bug
