Repository catalystneuro/roiextractors, pull requests merged in 2022-06, with the labels that each got.

#129 Add dummy imaging_extractor
  src/roiextractors/extractors/numpyextractors/numpyextractors.py
  src/roiextractors/testing.py
Labels: enhancement, testing

#131 Update numpy type hints
  src/roiextractors/extraction_tools.py
  src/roiextractors/extractors/nwbextractors/nwbextractors.py
  src/roiextractors/imagingextractor.py
Labels: low priority, refactor

#134 Small numpy typing PR
  src/roiextractors/extraction_tools.py
  src/roiextractors/imagingextractor.py
Labels: refactor

#138 CnmfeSegmentationExtractor roundtrip test working again
  src/roiextractors/extractors/schnitzerextractor/cnmfesegmentationextractor.py
  tests/test_io.py
Labels: low priority, testing

#137 Suit2p roundtrip test working again
  src/roiextractors/extractors/suite2p/suite2psegmentationextractor.py
Labels: low priority, testing

#142 Re enable `Suite2pSegmentationExtractor` round-trip
  tests/test_io.py
Labels: testing

#141 add typing information to `frame_slice in base` class
  src/roiextractors/imagingextractor.py
Labels: enhancement

#146 [Testing] testing if video shape is standard
  src/roiextractors/imagingextractor.py
  tests/test_io.py
Labels: testing

#136 Refactor nwb extractor frames and tests
  src/roiextractors/extractors/nwbextractors/nwbextractors.py
  src/roiextractors/testing.py
  tests/test_internals/test_nwb_extractors.py
Labels: bug, high priority, testing

#144 ScanImageTiffExtractor
  .github/workflows/testing.yml
  requirements-full.txt
  src/roiextractors/extractorlist.py
  src/roiextractors/extractors/tiffimagingextractor/__init__.py
  src/roiextractors/extractors/tiffimagingextractors/__init__.py
  src/roiextractors/extractors/tiffimagingextractors/scanimagetiffimagingextractor.py
  src/roiextractors/extractors/tiffimagingextractors/tiffimagingextractor.py
  tests/test_io.py
  tests/test_scan_image_tiff.py
Labels: enhancement

#151 Add Badges to main page
  README.md
Labels: documentation

#148 Swap suffix assertions to warnings (ImagingExtractors)
  src/roiextractors/extractors/hdf5imagingextractor/hdf5imagingextractor.py
  src/roiextractors/extractors/sbximagingextractor/sbximagingextractor.py
  src/roiextractors/extractors/tiffimagingextractors/tiffimagingextractor.py
Labels: warnings

#152 `num_rows`, `num_cols` terminology standarization
  src/roiextractors/extraction_tools.py
  src/roiextractors/extractors/memmapextractors/memmapextractors.py
  src/roiextractors/extractors/memmapextractors/numpymemampextractor.py
  src/roiextractors/extractors/numpyextractors/numpyextractors.py
  src/roiextractors/extractors/nwbextractors/nwbextractors.py
  src/roiextractors/extractors/tiffimagingextractors/scanimagetiffimagingextractor.py
  src/roiextractors/extractors/tiffimagingextractors/tiffimagingextractor.py
  src/roiextractors/testing.py
  tests/test_internals/test_extraction_tools.py
  tests/test_internals/test_frame_slice_imaging.py
  tests/test_numpymemmapextractor.py
Labels: refactor

#140 Hdf5 to standard video format
  src/roiextractors/extractors/hdf5imagingextractor/hdf5imagingextractor.py
Labels: low priority, testing, refactor

#158 Adding numpy indexing behavior to nwb_imaging_extractor
  src/roiextractors/testing.py
  tests/test_internals/test_nwb_extractors.py
Labels: enhancement, testing

#164 Test that sampling rate is float
  src/roiextractors/extractors/hdf5imagingextractor/hdf5imagingextractor.py
  src/roiextractors/extractors/memmapextractors/numpymemampextractor.py
  src/roiextractors/testing.py
  tests/test_io.py
Labels: testing, refactor

#163 Fix `ExtractSegmentationExtractor` roundtrip test
  src/roiextractors/extractors/schnitzerextractor/extractsegmentationextractor.py
  tests/test_io.py
Labels: bug, testing

#162 Add `folder_path` as an argument for `Suite2pSegmentationExtractor`
  src/roiextractors/extractors/suite2p/suite2psegmentationextractor.py
  tests/test_io.py
Labels: testing, refactor

#167 Synch setup installation methods with nwb conversion tools
  .github/workflows/testing.yml
  setup.py
Labels: low priority, refactor
